### ISSUE TITLE
Remove misleading mention of composing env variables that only works via `.env` files

### ISSUE THREAD

**Issue by yannickgloster** [prisma/prisma2-docs#2835]
Update: See problem in https://github.com/prisma/docs/issues/2835#issuecomment-1026293087

### Discussed in https://github.com/prisma/prisma/discussions/11453

<div type='discussions-op-text'>

<sup>Originally posted by **yannickgloster** January 27, 2022</sup>
Following prisma/prisma#1673, I converted the SSL Certificate that I needed from here [Azure Database for MySQL](https://docs.microsoft.com/en-us/azure/mysql/howto-configure-ssl) into base64 to store it in as an environment variable that I can then load in into the tmp folder on the serverless function. 
I do this when I create my prisma client:
`/lib/prisma.js`
```js
import { PrismaClient } from "@prisma/client";

const fs = require("fs");
const path = "/tmp";

try {
  if (fs.existsSync(`${path}/BaltimoreCyberTrustRoot.crt.pem`)) {
    // do nothing
  } else {
    // creates crt.pem file from ENV

    fs.mkdirSync(path, { recursive: true });

    fs.writeFileSync(
      `${path}/BaltimoreCyberTrustRoot.crt.pem`,
      Buffer.from(process.env.CRT_PEM, "base64").toString("ascii")
    );
  }
} catch (err) {
  console.error(err);
}

const prisma = global.prisma || new PrismaClient();

if (process.env.NODE_ENV === "development") global.prisma = prisma;

export default prisma;
```

Locally this works as expected, and when I check on the API endpoint, the file exists correctly
```js
import fs from "fs";

export default async function handler(req, res) {
  const files = fs.readFileSync(`/tmp/BaltimoreCyberTrustRoot.crt.pem`);

  res.status(200).json({ files: files.toString() });
}
```

My environment variables look like this:
```env
SSL_CERT_PATH=/tmp/BaltimoreCyberTrustRoot.crt.pem
DATABASE_URL=mysql://user:pass@lserverip:3306/registration?sslcert=${SSL_CERT_PATH}&connect_timeout=300
CRT_PEM=longbase64string
```

I'm able to successfully connect to the DB when I use those variables locally, but when deployed I get the following error when I go to make a request to the DB.
```
2022-01-27T23:22:08.847Z	c63d91bb-ae49-40c3-95dd-c20a224d3f4d	ERROR	PrismaClientInitializationError: Can't reach database server at `IP OF SERVER`:`3306`
Please make sure your database server is running at `IP OF SERVER`:`3306`.
    at cb (/var/task/node_modules/@prisma/client/runtime/index.js:38697:17)
    at async handler (/var/task/.next/server/pages/api/tournaments.js:60:25)
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:102:9)
    at async NextNodeServer.handleApiRequest (/var/task/node_modules/next/dist/server/base-server.js:1076:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/base-server.js:963:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:222:32)
    at async NextNodeServer.run (/var/task/node_modules/next/dist/server/base-server.js:1103:29)
    at async NextNodeServer.handleRequest (/var/task/node_modules/next/dist/server/base-server.js:319:20)
    at async Server.<anonymous> (/var/task/___next_launcher.js:32:9) {
  clientVersion: '3.8.1',
  errorCode: undefined
}
2022-01-27T23:22:08.847Z	c63d91bb-ae49-40c3-95dd-c20a224d3f4d	ERROR	PrismaClientInitializationError: Can't reach database server at `IP OF SERVER`:`3306`
Please make sure your database server is running at `IP OF SERVER`:`3306`.
    at cb (/var/task/node_modules/@prisma/client/runtime/index.js:38697:17)
    at async handler (/var/task/.next/server/pages/api/tournaments.js:60:25)
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:102:9)
    at async NextNodeServer.handleApiRequest (/var/task/node_modules/next/dist/server/base-server.js:1076:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/base-server.js:963:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:222:32)
    at async NextNodeServer.run (/var/task/node_modules/next/dist/server/base-server.js:1103:29)
    at async NextNodeServer.handleRequest (/var/task/node_modules/next/dist/server/base-server.js:319:20)
    at async Server.<anonymous> (/var/task/___next_launcher.js:32:9) {
  clientVersion: '3.8.1',
  errorCode: undefined
}
RequestId: c63d91bb-ae49-40c3-95dd-c20a224d3f4d Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

If I remove the SSL information from my DB connection string, I get an error stating that I need to provide SSL information to continue.
```Server error: `ERROR 28000 (9002): SSL connection is required. Please specify SSL options and retry.\u0000'```

Is there something I'm doing wrong here? 
Thanks in advance</div>

The reason I'm moving this to an issue is that due to the nature error, I believe this may be a bug.

**Comment by sontiO** [comment]
I just found this thread and I am so confused. How am I su

> I set the composed environment variables following what was written in the docs: https://www.prisma.io/docs/concepts/components/prisma-schema#accessing-environment-variables-from-the-schema
> 
> And they were uploaded to vercel using their UI that was documented here: https://vercel.com/docs/concepts/projects/environment-variables

so how am I supposed to set the env for vercel? I did just like you on those two documentations linked. I found this thread but still lost on what to do instead

**Comment by janpio** [comment]
Depends on what you want to to.
If you want to set a static env var: Use the Vercel instructions at the second link.
If you want to compose a new env var value out of other bits and pieces you have available: Use an `.env` file that just composes things together, use the first link.

**Comment by sontiO** [comment]
> 

I tried setting it static in Vercel UI. But I get:` ENOENT: no such file or directory, open '/var/task/schema.prisma' undefined` on my data in deployment. And my data obv undefined too.
Since it works locally, my first thought was something was wrong with my variant variable and this thread is the only thing i stumbled upon

**Comment by janpio** [comment]
That is completely unrelated to the env var problem and is probably related to the bundler you are using or something like that. Please open a new bug report issues in `prisma/prisma` about this if you can reproduce this. Thanks.

**Comment by Jolg42** [comment]
https://www.prisma.io/docs/guides/development-environment/environment-variables#expanding-variables
Clearly state 
>Variables stored in .env files can be expanded using the format specified by [dotenv-expand](https://github.com/motdotla/dotenv-expand).

But https://www.prisma.io/docs/concepts/components/prisma-schema#accessing-environment-variables-from-the-schema
> In version 2.7.0 and later, you can expand variables using the format specified by [dotenv-expand](https://github.com/motdotla/dotenv-expand). This is useful when dealing with PaaS or similar products. such as Heroku):

TODO: Could be improved, the fact that it only work with the `.env` file is implicit

**Comment by Jolg42** [comment]
I created a PR for the misleading text at https://github.com/prisma/docs/pull/4189

**Comment by Jolg42** [comment]
The misleading text was removed in https://github.com/prisma/docs/pull/4189
from https://www.prisma.io/docs/concepts/components/prisma-schema#accessing-environment-variables-from-the-schema
