### ISSUE TITLE
PDP: Investigate and document how queries run in the Query Console

### ISSUE THREAD

**Issue by zachtil** [prisma/prisma2-docs#3533]
The Query Console seems to respect malformed queries and still produce a result.

For example:

```
await prisma.post.findMany(
  select: didITypeTheCorrectThing
perhapsNot)
```
returns a pertinent list of results.

```
[
  {
    "id": 2,
    "createdAt": "2022-06-22T21:51:32.259Z",
    "updatedAt": "2022-06-22T21:51:32.260Z",
    "title": "Follow Prisma on Twitter",
    "content": "https://www.twitter.com/prisma",
    "published": true,
    "viewCount": 42,
    "authorId": 2
  },
  {
    "id": 3,
    "createdAt": "2022-06-22T21:51:32.892Z",
    "updatedAt": "2022-06-22T21:51:32.893Z",
    "title": "Ask a question about Prisma on GitHub",
    "content": "https://www.github.com/prisma/prisma/discussions",
    "published": true,
    "viewCount": 128,
    "authorId": 3
  },
...
```

The question was whether a badly formed `deleteMany` does the same. But it doesn't. For example:

```
await prisma.post.deleteMany({
 whhere: {
   post_id: 1
 } 
})
```
results in the following error:

```
[
  {
    "error": {
      "type": "PrismaClientUnknownRequestError",
      "code": "unknown",
      "message": "Unknown arg `whhere` in whhere for type AffectedRowsOutput. Did you mean `where`?\n",
      "stack": "Error: Unknown arg `whhere` in whhere for type AffectedRowsOutput. Did you mean `where`?\n\n    at Document.validate (/var/task/node_modules/@prisma/client/runtime/index.js:48195:20)\n    at PrismaClient._executeRequest (/var/task/node_modules/@prisma/client/runtime/index.js:50634:17)\n    at consumer (/var/task/node_modules/@prisma/client/runtime/index.js:50571:23)\n    at /var/task/node_modules/@prisma/client/runtime/index.js:50575:76\n    at runInChildSpan (/var/task/node_modules/@prisma/client/runtime/index.js:49780:12)\n    at /var/task/node_modules/@prisma/client/runtime/index.js:50575:20\n    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)\n    at PrismaClient._request (/var/task/node_modules/@prisma/client/runtime/index.js:50574:86)\n    at requestFn (/var/task/node_modules/@prisma/client/runtime/index.js:49316:65)\n    at /var/task/node_modules/@prisma/client/runtime/index.js:49329:18"
    }
  }
]
```

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
